# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="a8270ced-9879-42e1-b73f-d8da47bacc25"
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -igna@inbox.ru
    on_success: never # default: change
    on_failure: always # default: always